#!/bin/sh
ctags -R --c-kinds=+p --fields=+S
find $(pwd) -name "*.h"\
            -o -name "*.c"\
            -o -name "*.cpp"\
            -o -name '*.py'\
            -o -name '*.java'\
> cscope.files

# -b: just build
# -q: create inverted index
# -R: Recurse directories for files.
# -k: Kernel Mode - don't use /usr/include for #include files.
cscope -i cscope.files -Rbkq
